name: Docker Run

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '0 5 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_SENHA: ${{secrets.DOCKER_SENHA}}
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
      run: docker login -u $DOCKER_USER -p $DOCKER_SENHA
    - name: Docker Pull 
      run: docker pull impulsogov/impulsoprevine:latest
    - name: Docker Run
      run: docker run impulsogov/impulsoprevine:latest
    - name: Receber imagem Docker do ImpulsoETL
      run: docker pull impulsogov/impulsoetl:latest
    - name: Executar ImpulsoETL
      env:
        IMPULSOETL_BD_HOST: ${{secrets.IMPULSOETL_BD_HOST}}
        IMPULSOETL_BD_PORTA: ${{secrets.IMPULSOETL_BD_PORTA}}
        IMPULSOETL_BD_NOME: ${{secrets.IMPULSOETL_BD_NOME}}
        IMPULSOETL_BD_USUARIO: ${{secrets.IMPULSOETL_BD_USUARIO}}
        IMPULSOETL_BD_SENHA: ${{secrets.IMPULSOETL_BD_SENHA}}
      run: >
        docker run impulsogov/impulsoetl:latest
        --env IMPULSOETL_BD_HOST="$IMPULSOETL_BD_HOST"
        --env IMPULSOETL_BD_PORTA="$IMPULSOETL_BD_PORTA"
        --env IMPULSOETL_BD_NOME="$IMPULSOETL_BD_NOME"
        --env IMPULSOETL_BD_USUARIO="$IMPULSOETL_BD_USUARIO"
        --env IMPULSOETL_BD_SENHA="$IMPULSOETL_BD_SENHA"
