# SPDX-FileCopyrightText: 2021, 2022 ImpulsoGov <contato@impulsogov.org>
#
# SPDX-License-Identifier: MIT


name: Cria imagem Docker - ImpulsoETL

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'src/impulsoprevine/**',
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'src/impulsoprevine/**',
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_SENHA: ${{secrets.DOCKER_SENHA}}
        SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
      run: docker login -u $DOCKER_USER -p $DOCKER_SENHA
    - name: Construir imagem do ImpulsoETL
      run: >
        docker build -t impulsogov/impulsoetl:latest
        -f "./impulsoetl.Dockerfile" .
    - name: Enviar imagem do ImpulsoETL
      run: docker push impulsogov/impulsoetl
